### ISSUE TITLE
Counter variable not updating across different components

### ISSUE THREAD

**Issue by juskek** [juskek/app_architecture#1]
In reference to https://github.com/juskek/app_architecture/commit/4f5f89dff3c10002775ada2a725212af6c382a4c

![counter](https://github.com/juskek/app_architecture/assets/57725347/79b2b24c-75a6-4d9d-aae5-95e88d9e8024)

**Comment by justinkek** [comment]
Explanation:

- There are two View components, CounterView and OtherCounterView
- There are two ViewModels, CounterViewModel and OtherCounterViewModel
- There is a CounterRepository singleton created in the global scope with using createContext
- Within each ViewModel, 
  - The CounterRepository singleton is accessed with useContext
  - A useState hook is declared and initialised with the value of counterRepository.count, a count state variable and a private _setCounter variable
  - An increment function is exposed to the View, which calls counterRepository.increment() and also _setCounter(counterRepository.count)

The benefit of this approach is that when ViewModel.increment is called, it updates the data layer and also the view layer via counterRepository.increment() and _setCounter respectively

The drawback of this approach is that because useState is declared in the ViewModel layer, when different Views use different ViewModels, the useState hook is local to that ViewModel and hence _setCounter only updates the View it is called from

**Comment by justinkek** [comment]
Q: Can useState be moved into counterRepository instead?

useState is a React hook and needs to be called from within a functional component

https://github.com/juskek/app_architecture/commit/efe6e8c6609bda58137a8784b079508decc29806 Tried to implement this, but the view stopped updating when useState was moved into the repository

**Comment by justinkek** [comment]
Tried proposed solution (https://github.com/facebook/react/issues/26948) at the following commit: https://github.com/juskek/app_architecture/commit/c6bf33fe0bad1ac264bbe5cd0af374dfe9992b61

In this approach, a couple of patterns need to be implemented:

- Setup the repository so that listeners can subscribe to it 
  - Setup a listeners (aka observers) list in the repository, that will store listeners who are subscribed to the repository
  - Setup an addListener() to allow ViewModels to add themselves to the repository
  - Setup a removeListener() to allow ViewModels to remove themselves from the repository 
  - Setup notifyListeners() to tell all listeners that there is an update
- Create a ListenerType interface with an update function, that is invoked when repository.notifyListeners() is called 
- Setup ViewModel so that it listens to the repository 
  - Create a useState hook 
    - e.g. count, setCount
  - Invoke useEffect to run code after every render and have some cleanup before the next render or when the component unmounts
    - After every render,
      - Create a listener instance with an update implementation calling the useState setter, so that when repository calls notifyListeners, useState is updated and the View updates 
        - E.g. update calls setCount
    - Cleanup before next render or after unmount
      - Remove the listener from the repository


There is a lot of boilerplate for this approach, so could consider a combination of the two approaches (listener pattern with useState and useEffect + useState only)
- When state in the repository needs to be shared across multiple ViewModels, use listener pattern
- When state in repository only accessed by a single ViewModel, use useState only
  - Isn’t this method chaining? 
    - Yes, but it provides the benefit of separating logic for the view in ViewModel from logic for the data in Repository
      - E.g. if ViewModel had some variables for a UI component like a timer, and if Repository had Local and Remote data sources

see https://github.com/juskek/app_architecture/commit/c6bf33fe0bad1ac264bbe5cd0af374dfe9992b61
